{
  "openapi": "3.0.0",
  "info": {
    "title": "API with SOLID",
    "description": "This is an SOLID based API documentation",
    "version": "1.0.0",
    "contact": {
      "email": "brunog.knop@gmail.com"
    }
  },
  "components": {
    "schemas": {
      "userRequest": {
        "type": "object",
        "required": ["name", "email"],
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        }
      },
      "user": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "name": { "type": "string" },
          "created_at": { "type": "string" },
          "updated_at": { "type": "string" },
          "admin": { "type": "boolean" },
          "email": { "type": "string" }
        },
        "example": {
          "id": "6cfd4e5f-0138-42e3-a953-ade6ece55113",
          "name": "John Doe",
          "email": "johndoe@example.com",
          "admin": false,
          "created_at": "2022-06-17T05:42:25.202Z",
          "updated_at": "2022-06-17T05:42:25.202Z"
        }
      },
      "userAdmin": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "name": { "type": "string" },
          "created_at": { "type": "string" },
          "updated_at": { "type": "string" },
          "admin": { "type": "boolean" },
          "email": { "type": "string" }
        },
        "example": {
          "id": "6cfd4e5f-0138-42e3-a953-ade6ece55113",
          "name": "John Doe",
          "email": "johndoe@example.com",
          "admin": false,
          "created_at": "2022-06-17T05:42:25.202Z",
          "updated_at": "2022-06-17T05:42:25.202Z"
        }
      }
    },
    "examples": {}
  },
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "summary": "Create a new user",
        "description": "Create a new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/userRequest" },
              "example": {
                "name": "John Doe",
                "email": "johndoe@example.com"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/user/example" }
              }
            }
          },
          "400": {
            "description": "Error!"
          }
        }
      },
      "get": {
        "tags": ["Users"],
        "summary": "Only an admin can list users",
        "description": "Only an admin can list users",
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "description": "An administrator's id is required",
            "required": true,
            "explode": true,
            "schema": {
              "type": "string",
              "example": "6cfd4e5f-0138-42e3-a953-ade6ece55113"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/user" },
                "example": [
                  {
                    "id": "6cfd4e5f-0138-42e3-a953-ade6ece55113",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "admin": false,
                    "created_at": "2022-06-17T05:42:25.202Z",
                    "updated_at": "2022-06-17T05:42:25.202Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Error!",
            "content": {
              "application/json": {
                "example": {
                  "error": "User without permition!"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Get user by id",
        "description": "Get user by id",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "An id is required",
            "required": true,
            "explode": true,
            "schema": {
              "type": "string",
              "example": "6cfd4e5f-0138-42e3-a953-ade6ece55113"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/user" }
              }
            }
          },
          "404": {
            "description": "Error!",
            "content": {
              "application/json": {
                "example": {
                  "error": "User does not exists!"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["Users"],
        "summary": "Turn an user admin",
        "description": "Turn an user admin",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "Required id of an user",
            "required": true,
            "explode": true,
            "schema": {
              "type": "string",
              "example": "6cfd4e5f-0138-42e3-a953-ade6ece55113"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success!",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/userAdmin" }
              }
            }
          },
          "404": {
            "description": "Error!",
            "content": {
              "application/json": {
                "example": {
                  "error": "User does not exists!"
                }
              }
            }
          }
        }
      }
    }
  }
}